#!/command/with-contenv bash
set -euo pipefail

############ Dashboard
if [[ ! -f /opt/data/dashboard_secret ]]; then
    echo "Dashboard secret not found, generating a new one..."
    openssl rand -base64 32 > /opt/data/dashboard_secret
fi
if [[ -z "$(jq -r .dashboard.username /opt/data/options.json)" ]]; then
    echo "ERROR: Dashboard username not set!"
    exit 1
fi
if [[ -z "$(jq -r .dashboard.password /opt/data/options.json)" ]]; then
    echo "ERROR: Dashboard password not set!"
    exit 1
fi
printf '%s' "$(jq -r .dashboard.username /opt/data/options.json)" > /var/run/s6/container_environment/HERMES_DASHBOARD_BASIC_AUTH_USERNAME
printf '%s' "$(jq -r .dashboard.password /opt/data/options.json)" > /var/run/s6/container_environment/HERMES_DASHBOARD_BASIC_AUTH_PASSWORD
printf '%s' "$(cat /opt/data/dashboard_secret)" > /var/run/s6/container_environment/HERMES_DASHBOARD_BASIC_AUTH_SECRET

############ API Server
if [[ "$(jq -r .api_server.enabled /opt/data/options.json)" == "true" ]]; then
    if [[ -z "$(jq -r .api_server.key /opt/data/options.json)" ]]; then
        echo "ERROR: API server key not set!"
        exit 1
    fi
    printf '%s' "true" > /var/run/s6/container_environment/API_SERVER_ENABLED
    printf '%s' "$(jq -r .api_server.key /opt/data/options.json)" > /var/run/s6/container_environment/API_SERVER_KEY
else
    printf '%s' "false" > /var/run/s6/container_environment/API_SERVER_ENABLED
fi

############ HAProxy
mkdir -p /etc/haproxy
if [[ "$(jq -r .ssl_enabled /opt/data/options.json)" == "true" ]]; then
    (
        umask 077
        cat "/ssl/$(jq -r .ssl.certfile /opt/data/options.json)" "/ssl/$(jq -r .ssl.keyfile /opt/data/options.json)" >/etc/haproxy/cert-and-key.pem
    )
    HAPROXY_SSL="ssl crt /etc/haproxy/cert-and-key.pem"
else
    HAPROXY_SSL=
fi
if [[ "$(jq -r .api_server.enabled /opt/data/options.json)" == "true" ]]; then
    HAPROXY_API_SERVER=
else
    HAPROXY_API_SERVER="#"
fi
cat >/etc/haproxy/haproxy.cfg <<EOF 
global
    maxconn 2048

defaults
    log     global
    timeout connect 5s
    timeout client  1m
    timeout server  1m

${HAPROXY_API_SERVER}frontend fe_8642
${HAPROXY_API_SERVER}    mode http
${HAPROXY_API_SERVER}    bind *:8642 ${HAPROXY_SSL}
${HAPROXY_API_SERVER}    default_backend bk_18642
${HAPROXY_API_SERVER}
${HAPROXY_API_SERVER}backend bk_18642
${HAPROXY_API_SERVER}    mode http
${HAPROXY_API_SERVER}    option forwarded
${HAPROXY_API_SERVER}    option forwardfor
${HAPROXY_API_SERVER}    server local_18642 127.0.0.1:18642

frontend fe_9119
    mode http
    bind *:9119 ${HAPROXY_SSL}
    default_backend bk_19119

backend bk_19119
    mode http
    option http-server-close
    option forwarded
    option forwardfor
    timeout tunnel 1h
    server local_19119 127.0.0.1:19119

frontend ingress_8099
    mode http
    bind *:8099
    http-request deny if !{ src 172.30.32.2 }
    http-request set-header X-Forwarded-Prefix %[req.hdr(X-Ingress-Path)]
    default_backend bk_19119

EOF
