name: "Hermes Agent"
description: "A deployment configuration for Hermes Agent as a Home Assistant app."
version: "1.0.21"
slug: "hermes-hass-deployment"
init: false
arch:
  - amd64
  - aarch64
map:
  - type: data
    read_only: false
    path: /opt/data
  - type: ssl
ports:
  8642/tcp: 8642
  9119/tcp: 9119
webui: "[PROTO:ssl_enabled]://[HOST]:[PORT:9119]/"
environment:
  API_SERVER_HOST: "127.0.0.1"
  API_SERVER_PORT: "18642"
  API_SERVER_CORS_ORIGINS: "*"
  HERMES_DASHBOARD: "true"
  # Unfortunately, 0.0.0.0 is needed otherwise Hermes will not enable the Basic-auth flow.
  # But the port is not exposed by Docker anyways.
  HERMES_DASHBOARD_HOST: "0.0.0.0"
  HERMES_DASHBOARD_PORT: "19119"
options:
  dashboard:
    username: ""
    password: ""
  api_server:
    enabled: false
    key: ""
  ssl_enabled: false
  ssl:
    certfile: ""
    keyfile: ""
schema:
  dashboard:
    username: str
    password: password
  api_server:
    enabled: bool
    key: password
  ssl_enabled: bool
  ssl:
    certfile: str
    keyfile: str
